name: CI-SFTP
 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "SFTP"
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: create tar
        run: zip -r deploy.zip .     
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: ubuntu
          server: 140.238.248.146
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.KEY }}
          password: 6+skEQGVckPm
          #ssh_password: ${{ secrets.PASSWORD }}
          local_path: ./deploy.zip # default is ./*
          remote_path: /var/www/html/demo.erelego.com
          #args: '-o ConnectTimeout=10'
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
           unzip /var/www/html/demo.erelego.com/deploy.zip -d /var/www/html | sudo rm -rf /var/www/html/demo.erelego.com/deploy.zip
          host: 140.238.248.146
          user: ubuntu
          key: ${{ secrets.KEY }}
          #ssh_password: ${{ secrets.PASSWORD }}
          port: 22
          password: 6+skEQGVckPm
          args: "-tt -vvv"
          
         
          
          
      
       
